---
# App settings
app:
  global:
    image: wger/server:{{ .Chart.AppVersion }}
  ingress:
    enabled: true
    url: fit.example.com
    tls: true
    annotations: {}
  persistence:
    enabled: true
    annotations: {}
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  annotations: {}
  environment:
    - name: TIME_ZONE
      value: UTC
    - name: ENABLE_EMAIL
      value: "False"

# PostgreSQL Settings. Only the bare minimum has been specified below.
# For more options, see https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  # Note: keep these variables present as the chart uses them for the StatefulSet
  global:
    postgresqlDatabase: wger
    postgresqlUsername: wger
    postgresqlPassword: wger
    servicePort: 5432
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m
  persistence:
    enabled: true
    mountPath: /bitnami/postgresql
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

# Redis Settings. Only the bare minimum has been specified below.
# For more options, see https://github.com/bitnami/charts/tree/master/bitnami/redis
redis:
  # Note: keep these variables present as the chart uses them for the StatefulSet
  auth:
    password: wger
    enabled: true
    sentinel: true
  master:
    containerPort: 6379
    persistence:
      enabled: true
      path: /data
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi