---
apiVersion: v2
name: wger
description: A Helm chart for Wger installation on Kubernetes
type: application
version: 0.1.1
appVersion: 2.1.0
dependencies:
  - name: postgresql
    version: 11.6.7
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 16.12.2
    repository: https://charts.bitnami.com/bitnami